### ISSUE TITLE
Questions with forcing Java 7 to use TLS 1.2

### ISSUE THREAD

**Issue by wheata03** [bitmovin/bitmovin-java#41]
https://github.com/bitmovin/bitmovin-java/blob/fbdeffca2a1d307daddece67e554128efbb343e1/src/main/java/com/bitmovin/api/BitmovinApi.java#L108

Is it possible to supply more background to this logic?
- Why is `1.7.0` special for requiring TLS 1.2, do other versions (6?, 8?, 9? 10?) have it enabled by default?
- TLS 1.3 will be available before Java 7 is EOL.
- The TLS implementation should negotiate with the server to decide which version to use.

**Comment by rkersche** [comment]
Our API requires TLS 1.2. Java 7 however, has TLS 1.2 not enabled by default. 
https://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html#tlsprotonote

Java 8 however has: https://blogs.oracle.com/java-platform-group/jdk-8-will-use-tls-12-as-default
