### ISSUE TITLE
S3 Role Based Access while passing the Role Arn not working with encoding

### ISSUE THREAD

**Issue by manojchaulagain** [bitmovin/bitmovin-java#93]
Goal: Encoding the video content. 
We were using the S3Output with accessKey and secretKey and it worked just fine.

Trying to change the encoding output from S3Output to S3 Role Based Output. 
S3Output worked just fine with the accessKey and secretKey
S3RoleBasedOutput is not working while passing the roleArn created for bitmovin cross account role.

We have created a cross account Role Bitmovin to access the S3 Bucket. We have set up all the roles mentioned in the link below.

https://bitmovin.com/docs/analytics/tutorials/how-to-export-bitmovin-analytics-to-an-s3-role-based-bucket 

Usage in code to set up S3RoleBasedOutput for bitmovin 

```
        S3RoleBasedOutput output = new S3RoleBasedOutput();
        output.setCloudRegion( AwsCloudRegion.US_WEST_2 );
        output.setBucketName( S3_OUTPUT_BUCKET_NAME );
        output.setRoleArn( BitmovinSettings.AWS_S3_ROLE_ARN );

```

Is there any additional details we are missing while we get this set up? It would really nice if we could get some insight on this.

**Comment by LudoMichaud** [comment]
hi @manojchaulagain 
Thanks for reaching out.
Please could you let me know which error you are seeing ?
In addition, I would recommend to continue the conversation via email at support@bitmovin.com, so it's easier for you and me to share further details. 

Thanks in advance.

**Comment by manojchaulagain** [comment]
Thank you reaching out quickly. Will do that.
